### ISSUE TITLE
Torhsht deposu ekledikten sonraki güncelleme hatası

### ISSUE THREAD

**Issue by HknMurat** [HackerAdana/torhsht#1]
selamlar programı yayınlamıssınız hayırlı olsun diyelim :)
toshsht yle tor deposunu ekledikten sonra apt-get update çıktısında aşağıdaki hatayı veriyor. ben depoyu kaldırarak sorunu çözdüm. buna çözüm bulursanız iyi olur kolay gelsin :)

> W: Packages (main/binary-i386/Packages) hedefi /etc/apt/sources.list.d/resmi-depolar.list:19 ve /etc/apt/sources.list.d/torhsht_tor_repos.list:2 konumlarında birden fazla kez yapılandırılmış
> W: Packages (main/binary-all/Packages) hedefi /etc/apt/sources.list.d/resmi-depolar.list:19 ve /etc/apt/sources.list.d/torhsht_tor_repos.list:2 konumlarında birden fazla kez yapılandırılmış
> W: Translations (main/i18n/Translation-tr_TR) hedefi /etc/apt/sources.list.d/resmi-depolar.list:19 ve /etc/apt/sources.list.d/torhsht_tor_repos.list:2 konumlarında birden fazla kez yapılandırılmış
> W: Translations (main/i18n/Translation-tr) hedefi /etc/apt/sources.list.d/resmi-depolar.list:19 ve /etc/apt/sources.list.d/torhsht_tor_repos.list:2 konumlarında birden fazla kez yapılandırılmış
> W: Translations (main/i18n/Translation-en) hedefi /etc/apt/sources.list.d/resmi-depolar.list:19 ve /etc/apt/sources.list.d/torhsht_tor_repos.list:2 konumlarında birden fazla kez yapılandırılmış
> W: Packages (main/binary-i386/Packages) hedefi /etc/apt/sources.list.d/resmi-depolar.list:19 ve /etc/apt/sources.list.d/torhsht_tor_repos.list:2 konumlarında birden fazla kez yapılandırılmış
> W: Packages (main/binary-all/Packages) hedefi /etc/apt/sources.list.d/resmi-depolar.list:19 ve /etc/apt/sources.list.d/torhsht_tor_repos.list:2 konumlarında birden fazla kez yapılandırılmış
> W: Translations (main/i18n/Translation-tr_TR) hedefi /etc/apt/sources.list.d/resmi-depolar.list:19 ve /etc/apt/sources.list.d/torhsht_tor_repos.list:2 konumlarında birden fazla kez yapılandırılmış
> W: Translations (main/i18n/Translation-tr) hedefi /etc/apt/sources.list.d/resmi-depolar.list:19 ve /etc/apt/sources.list.d/torhsht_tor_repos.list:2 konumlarında birden fazla kez yapılandırılmış
> W: Translations (main/i18n/Translation-en) hedefi /etc/apt/sources.list.d/resmi-depolar.list:19 ve /etc/apt/sources.list.d/torhsht_tor_repos.list:2 konumlarında birden fazla kez yapılandırılmış
>

**Comment by HackerAdana** [comment]
Merhaba @HknMurat, ilginiz için teşekkür ederiz. Sorunu çözmenize sevindik :blush:

Repoların çakışmasıyla ilgili düzenlemeyi en kısa sürede yapacağımızdan emin olabilirsiniz.
ok by :wave: :laughing:

**Comment by AnarsistYazilimci** [comment]
Merhaba @HknMurat ilgili düzeltmeyi 0.4-beta sürümünde yaptık.
0.4~beta sürümü itibariyle, Tor reposu eklenmişse Torhsht ilgili depoyu sisteme eklemeyecek.

0.4-beta sürümünü önümüzdeki bir kaç gün içinde commit etmeyi planlıyoruz.

**Comment by HknMurat** [comment]
Sagolun beyler şunu da bakar mısınız https://github.com/HackerAdana/torhsht/issues/2

**Comment by AnarsistYazilimci** [comment]
Biz teşekkür ederiz @HknMurat. 

Başlık düzeltmeyi yayınlayana kadar açık kalsın.

**Comment by AnarsistYazilimci** [comment]
@HknMurat İlgili düzeltmeyi 0.4~beta güncellemesi ile yaptık. Artık Tor reposu sisteme eklenmişse, Torhsht Tor reposunu sisteme eklemeyecek. Lakin anahtar doğrulaması yapacak. Anahtarlar birbirini tutuyorsa kuruluma devam edecek.
