### ISSUE TITLE
meek ekleme hatası

### ISSUE THREAD

**Issue by HknMurat** [HackerAdana/torhsht#2]
meek köprülerini eklemek istedigimde asagıdaki hataı almaktayım.

```
 [**] 'meek-bridge' için 'git' paketine ihtiyacımız var..
 [**] 'git' paketini kontrol ediyoruz..
 [**] 'git' paketinin sisteminizde kurulu olduğunu farkettik..
 [**] 'meek-bridge' için gereken dizinleri oluşturuyoruz..
 [**] 'meek' köprülerini ediniyoruz..
 [**] 'golang-go' paketini kontrol ediyoruz..
 [**] 'golang-go' paketininin kurulu olduğunu farkettik..
 [**] 'meek' paketini derliyoruz..
 [**] 'meek' paketini derledik..
 [**] 'meek' için 'torrc' dosyası düzenlemek üzere açıyoruz..
 [**] 'meek' köprülerini 'torrc' dosyasına yazıyoruz..
Traceback (most recent call last):
  File "../torhsht.py", line 51, in <module>
    treat.meekbridge()
  File "/home/hknmurat/torhsht/Modules/treat.py", line 132, in meekbridge
    "ClientTransportPlugin meek exec " + homedir + "/.HackerAdana/Torhsht/meek/meek-client/meek-client --log "  + homedir + "/.HackerAdana/Torhsht/meek/meek-client/meek-client.log\n"])
TypeError: cannot concatenate 'str' and 'list' objects

```

**Comment by AnarsistYazilimci** [comment]
Sorunu çözdük demiştik ama çözememişiz demek ki :expressionless: Teşekkür ederiz @HknMurat. 
0.4~beta sürümünde bu hata ile ilgili bir düzenleme yapacağız.

**Comment by HackerAdana** [comment]
treat.py dosyasının 113. satırını aşağıdaki şekilde düzenlemek geçici çözüm olabilir.
```
torrc3.writelines(["\n" + "## TORHSHT Hacker Adana Meek Bridge" + lines[0] + lines[6] + lines[7] +
			"ClientTransportPlugin meek exec " + homedir + "/.HackerAdana/Torhsht/meek/meek-client/meek-client --log "  + homedir + "/.HackerAdana/Torhsht/meek/meek-client/meek-client.log\n"])
```

**Comment by AnarsistYazilimci** [comment]
@HknMurat 0.4~beta güncellemesini yayınladık. Biz bir kaç deneme yaptık, sorunla karşılaşmadık. Sizde geribildirimde bulunursanız başlığı yoruma kapatabiliriz.

**Comment by HknMurat** [comment]
Denemeyi kendi sisteminizde mi yaptınız ;D 
Sorun hala devam ediyor ama farklı bir sorun. yine mek bridge ile ilgili. son yayınladığınız güncellemeden sonra kurulum ilerlemiyor.

```
 Meek köprülerini 'torrc' dosyasına eklemek istiyor musunuz?
[E/h] > e
 [**] 'meek-bridge' işlemi başlıyor.. 

 [**] meek-bridge için gereken paketleri kontrol ediyoruz..
 [!] İhtiyacımız olan paketleri bulamadık..
 Şimdi yüklüyoruz..
 [**] Depo önbelleğini güncelliyoruz..
 [+] Depo önbelleğini güncelledik..
 [+] 'git' ve 'golang-go' paketini kurduk..
 [**] 'meek' köprüleri için yeniden deniyoruz..
 [**] 'meek-bridge' işlemi başlıyor.. 

 [**] meek-bridge için gereken paketleri kontrol ediyoruz..
 [!] İhtiyacımız olan paketleri bulamadık..
 Şimdi yüklüyoruz..
 [**] Depo önbelleğini güncelliyoruz..
 [+] Depo önbelleğini güncelledik..
```

**Comment by HknMurat** [comment]
Ek olarak kurulum tamamlandı ama aradaki hatayı veriyor.
```
 [**] Tor kurulumu başlıyor..

 [**] Sisteminizin tabanına bakıyoruz..
 [+] Torhsht, Kullandığınız Ubuntu sürümünü destekliyor..
 [**] Çakışmaları önlemek için depoları kontrol ediyoruz..
cat: '/etc/apt/sources.list.d/*': No such file or directory
 [+] Sisteminize eklenmiş bir 'torproject.org' reposu bulamadık..
 [**] Tor reposunu oluşturuyoruz..
 [+] Depo dosyasını oluşturduk..
 [**] Repo anahtarlarını içe aktarıyoruz..
 [+] Anahtar dosyası içe aktardık..
 [**] Depo önbelleğini güncelliyoruz..
 [+] Depo önbelleği güncelledik..
 [**] 'tor' paketini kuruluyoruz..
 [+] 'tor' paketini kurduk..

 [++] Tor kurulumu tamamlandı.. :) 
```

**Comment by HackerAdana** [comment]
> cat: '/etc/apt/sources.list.d/*': No such file or directory

Kullandığınız dağıtım depo adreslerini sources.list dosyasında saklıyor sanırım. Haliyle sources.list.d dizini olmadığı için depo dosyaları da yok. Torhsht ise sources.list.d dizini altındaki dosyalarda torproject reposunu arıyor.  Bununla ilgili bir düzenleme yapacağız. :+1:

**Comment by AnarsistYazilimci** [comment]
> Denemeyi kendi sisteminizde mi yaptınız ;D

Hayır Gitlab üzerinde ve bir canlı CD üzerinde yaptık.  :stuck_out_tongue: Siz bu işlemi yapmaya çalıştığınızda başka bir uygulama APT'yi kullanıyor olmasın? 

https://github.com/HackerAdana/torhsht/issues/2#issuecomment-307847130 ile ilgili açıklamayı @HackerAdana yapmış. 
Şu ana kadar bildiğimiz bug, meek-bridge eklemek istediğinizde herhangi bir hata alırsanız ve gereken paketleri yükleyemezseniz sonsuz bir döngü oluşuyor. CTRL + C ile de işlemi sonlandıramıyorsunuz, tek yapabileceğiniz pencereyi kapatmak. Bunun üzerinde çalışıyoruz.

>  [+] 'git' ve 'golang-go' paketini kurduk..'git' ve 'golang-go'

Bug'a çözüm olarak aşağıdaki komut ile **git** ve **golang-go** paketi yüklenebilir.
`sudo apt-get install git golang-go`

Ek olarak bu sürümdeki bug'lar için düzeltme yayınlayacağız. 0.5~beta sürümünü beklemenize gerek yok. :stuck_out_tongue_winking_eye:

**Comment by HackerAdana** [comment]
@HknMurat Bahsettiğim sources.list sorununu ve @AnarsistYazilimci arkadaşımızın bahsettiği sorunu 0.4~beta2 güncellemesi ile çözdük. Ben başlığı kapatıyorum. Eğer bir sorun yaşarsanız yeni bir issue açabilirsiniz. Geribildiriminiz için teşekkür ederiz.
